name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  # Actualiza a la última versión
    - name: Set up Node.js
      uses: actions/setup-node@v3  # Actualiza a la última versión
      with:
        node-version: '20'  # Usa la versión más reciente de Node.js
    - run: npm install
    - run: npm test

